version: "3.8"
services:
  miner:
    image: giansalex/monero-miner
    container_name: monero-miner
    privileged: true
    cap_add:
      - ALL
    volumes:
      - "/lib/modules:/lib/modules"
    environment:
      WALLET: ${WALLET}
      POOL: ${POOL}
      WORKER_NAME: ${WORKER_NAME}
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 2G
    restart: always
